<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Commands\Products\CreateProduct\CreateProductCommandHandler.cs~RF46c7a1.TMP" />
    <None Remove="Commands\Products\CreateProduct\CreateProductCommandValidator.cs~RF3578d7.TMP" />
    <None Remove="Commands\Users\CreateUser\CreateUserCommandHandler.cs~RF490a2e.TMP" />
    <None Remove="Commands\Ypks\CreateYpk\CreateYpkCommandHandler.cs~RF4a869d.TMP" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="AutoMapper" Version="13.0.1" />
	  <PackageReference Include="FluentValidation" Version="8.6.3" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="8.6.3" />
	  <PackageReference Include="MediatR" Version="11.1.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
